### ISSUE TITLE
Cannot Build in Unity 2017.1.1f1

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/RoomAliveToolkit#75]
Hi, when trying to build in Unity 2017.1.1f1 I am returned the following, Assets/RoomAliveToolkit/Scripts/RATSceneSetup.cs(3,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?

Any suggestions on how to properly build to a .exe for a room alive scene in Unity 2017?

Thanks!

-Reilly

**Comment by thundercarrot** [comment]
I'm not sure why we're seeing this issue only now, but it does make sense that you wouldn't have access to the UnityEditor namespace in a build. See 
https://answers.unity.com/questions/316805/unityeditor-namespace-not-found.html
for example.

Can you try putting that file in the Editor folder and see if that fixes it?

I may not have time soon to take a look myself.

**Comment by jjhartmann** [comment]
I came across this same issue, and the fix was to wrap the UnityEditor could in a macro.

Line: 3
```C#
#if UNITY_EDITOR
using UnityEditor;
#endif
```

and lines: 37-41

```C#
#if UNITY_EDITOR
        public void LoadDefault3DModels()
        {
            kinectModel = AssetDatabase.LoadAssetAtPath<GameObject>("Assets/RoomAliveToolkit/Models/Kinect.obj");
            projectorModel = AssetDatabase.LoadAssetAtPath<GameObject>("Assets/RoomAliveToolkit/Models/Projector.obj");
        }
#endif
```
